# Autoregressive Causal Language Model from Scratch

## Overview

An Autoregressive Language Model predicts the next token in a sequence using only the previous tokens. This notebook demonstrates a simple implementation after building a BPE tokenizer.

### Implementation Steps
1. Read the corpus
2. Split words into characters
3. Build vocabulary
4. Create input-target pairs
5. Create embeddings
6. Positional encoding
7. Generate predictions

In [5]:
import numpy as np

print("Autoregressive Causal Language Model")

Autoregressive Causal Language Model


In [6]:
with open("corpus.txt", "w") as file:
    file.write("""low
lower
lowest
new
newer
widest""")

print("corpus.txt created successfully!")

corpus.txt created successfully!


## Step 1: Read the Corpus

In [7]:
def read_corpus(filename):
    words = []

    with open(filename, "r") as file:
        for line in file:
            line = line.strip().lower()
            if line:
                words.append(line)

    return words


corpus = read_corpus("corpus.txt")

print("Corpus:\n")

for word in corpus:
    print(word)

Corpus:

low
lower
lowest
new
newer
widest


## Step 2: Split Words into Characters

In [8]:
tokens = []

for word in corpus:
    token = list(word)
    tokens.append(token)

print("Character Tokens:\n")

for token in tokens:
    print(token)

Character Tokens:

['l', 'o', 'w']
['l', 'o', 'w', 'e', 'r']
['l', 'o', 'w', 'e', 's', 't']
['n', 'e', 'w']
['n', 'e', 'w', 'e', 'r']
['w', 'i', 'd', 'e', 's', 't']


## Step 3: Build Vocabulary

In [9]:
vocab = sorted(set("".join(corpus)))

print("Vocabulary:\n")
print(vocab)

print("\nVocabulary Size:", len(vocab))

Vocabulary:

['d', 'e', 'i', 'l', 'n', 'o', 'r', 's', 't', 'w']

Vocabulary Size: 10


## Step 4: Create Input–Target Pairs

In [10]:
input_sequences = []
target_tokens = []

for word in corpus:
    chars = list(word)

    for i in range(len(chars) - 1):
        input_sequences.append(chars[:i+1])
        target_tokens.append(chars[i+1])

print("Input → Target\n")

for x, y in zip(input_sequences, target_tokens):
    print(x, "→", y)

Input → Target

['l'] → o
['l', 'o'] → w
['l'] → o
['l', 'o'] → w
['l', 'o', 'w'] → e
['l', 'o', 'w', 'e'] → r
['l'] → o
['l', 'o'] → w
['l', 'o', 'w'] → e
['l', 'o', 'w', 'e'] → s
['l', 'o', 'w', 'e', 's'] → t
['n'] → e
['n', 'e'] → w
['n'] → e
['n', 'e'] → w
['n', 'e', 'w'] → e
['n', 'e', 'w', 'e'] → r
['w'] → i
['w', 'i'] → d
['w', 'i', 'd'] → e
['w', 'i', 'd', 'e'] → s
['w', 'i', 'd', 'e', 's'] → t


## Step 5: Create Token IDs

In [11]:
token_to_id = {token: idx for idx, token in enumerate(vocab)}
id_to_token = {idx: token for token, idx in token_to_id.items()}

print("Token to ID Mapping\n")
print(token_to_id)

Token to ID Mapping

{'d': 0, 'e': 1, 'i': 2, 'l': 3, 'n': 4, 'o': 5, 'r': 6, 's': 7, 't': 8, 'w': 9}


## Step 6: Convert Tokens to IDs

In [12]:
encoded_inputs = []

for sequence in input_sequences:
    encoded_inputs.append([token_to_id[ch] for ch in sequence])

print("Encoded Inputs\n")

for item in encoded_inputs:
    print(item)

Encoded Inputs

[3]
[3, 5]
[3]
[3, 5]
[3, 5, 9]
[3, 5, 9, 1]
[3]
[3, 5]
[3, 5, 9]
[3, 5, 9, 1]
[3, 5, 9, 1, 7]
[4]
[4, 1]
[4]
[4, 1]
[4, 1, 9]
[4, 1, 9, 1]
[9]
[9, 2]
[9, 2, 0]
[9, 2, 0, 1]
[9, 2, 0, 1, 7]


## Step 7: Create Embedding Matrix

In [13]:
embedding_dim = 8

embedding_matrix = np.random.rand(len(vocab), embedding_dim)

print("Embedding Matrix Shape:")
print(embedding_matrix.shape)

Embedding Matrix Shape:
(10, 8)


## Step 8: Positional Encoding

In [14]:
max_length = 10

positions = np.arange(max_length)

print("Positions:")
print(positions)

Positions:
[0 1 2 3 4 5 6 7 8 9]


## Step 9: Create Causal Mask

In [15]:
sequence_length = 6

causal_mask = np.tril(np.ones((sequence_length, sequence_length)))

print("Causal Mask:\n")
print(causal_mask)

Causal Mask:

[[1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1.]]


## Step 10: Compute Self-Attention

In [16]:
attention_scores = np.random.rand(sequence_length, sequence_length)

masked_attention = attention_scores * causal_mask

print("Masked Attention Matrix:\n")
print(masked_attention)

Masked Attention Matrix:

[[0.89444567 0.         0.         0.         0.         0.        ]
 [0.39947578 0.87883943 0.         0.         0.         0.        ]
 [0.24357704 0.0298855  0.71729511 0.         0.         0.        ]
 [0.98075557 0.21214198 0.86290372 0.63774037 0.         0.        ]
 [0.76518581 0.09274155 0.93340807 0.75063596 0.02504515 0.        ]
 [0.21685801 0.64184212 0.91954926 0.6756384  0.20220789 0.20860338]]


## Step 11: Linear Layer

In [17]:
output = np.random.rand(sequence_length, len(vocab))

print("Linear Layer Output Shape:")
print(output.shape)

Linear Layer Output Shape:
(6, 10)


## Step 12: Softmax

In [18]:
def softmax(x):
    exp = np.exp(x - np.max(x))
    return exp / exp.sum()

probabilities = softmax(output[0])

print("Softmax Probabilities:\n")
print(probabilities)

Softmax Probabilities:

[0.09765764 0.11029879 0.11547376 0.12091408 0.08926648 0.06036074
 0.14988377 0.10083281 0.09028994 0.06502198]


## Step 13: Predict Next Token

In [19]:
predicted_id = np.argmax(probabilities)

predicted_token = id_to_token[predicted_id]

print("Predicted Token:", predicted_token)

Predicted Token: r


## Step 14: Generate Text

In [20]:
seed = "lo"

generated = seed + predicted_token

print("Generated Text:")
print(generated)

Generated Text:
lor


# Conclusion

This notebook demonstrated the basic workflow of an Autoregressive Causal Language Model after tokenization. It included:

- Reading the corpus
- Character tokenization
- Vocabulary creation
- Token ID mapping
- Input-target pair generation
- Embedding matrix
- Positional encoding
- Causal masking
- Self-attention simulation
- Softmax prediction
- Next-token generation

This is a simplified educational implementation that demonstrates the core concepts behind autoregressive language models.